name: taxi_booking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_api_headers: ^2.0.0
  # TOAST
  fluttertoast: ^8.2.14

  # IMAGE
  cached_network_image: ^3.4.1

  # BASE
  intl: ^0.18.1
  google_fonts: ^6.3.3
  html: ^0.15.6
  shared_preferences: ^2.5.4
  flutter_widget_from_html: ^0.17.1

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.3
  lottie: ^3.3.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.11.2
  country_code_picker: ^3.4.1
  flutter_native_contact_picker: ^0.0.11
  dotted_border: ^2.1.0
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  permission_handler: ^12.0.1

  #OTP TEXTFIELD
#  otp_text_field: ^1.1.3
  pinput: ^6.0.1
#  flutter_otp_text_field: ^1.1.3+2

  # MAP
  geolocator: ^10.0.1
#  geolocator: ^12.0.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  google_maps_place_picker_mb: ^3.1.2

  # IMAGES
  image_picker: ^1.2.1
  file_picker: ^10.3.7

  # CONNECTIVITY
  package_info_plus: ^4.2.0

  # CONNECTIVITY
  http: ^0.13.6
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  internet_file: ^1.3.0

  #FIREBASE
  firebase_crashlytics: ^4.3.8
  firebase_core: ^2.32.0
  firebase_auth: ^5.6.1
  firebase_storage: ^12.4.8
  firebase_database: ^11.3.8
  paginate_firestore: ^1.0.3+1
#  paginate_firestore:
#    path: ./lib/my_packages/paginate_firestore-master
#  flutter_paystack:
#    path: ./lib/my_packages/flutter_paystack-1.0.7
  cloud_firestore: ^5.6.10

  # STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # Payment gateway
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^11.5.0
#  flutter_paystack:
#    git:
#      url: https://github.com/appmeetmighty/flutter_paystack.git
#    path: ./lib/package/flutter_paystack-master
#  flutter_paystack: ^1.0.7
#  flutter_braintree: ^4.0.0
  flutterwave_standard: ^1.1.0
  flutter_paytabs_bridge: ^2.7.3
#  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  my_fatoorah: ^3.5.0
#  paytm: ^3.0.1


  # PUSH NOTIFICATION
  onesignal_flutter: ^5.3.4

  # MQTT
#  mqtt_client: ^10.2.0

  # Social Login
  google_sign_in: ^7.2.0
  the_apple_sign_in: ^1.1.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.11.1
  pdfx: ^2.9.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  printing: ^5.14.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  package_info_plus: ^4.2.0
  intl: ^0.18.1
  http: ^0.13.6
  cloud_firestore: ^5.6.10
  firebase_core: ^2.32.0
  google_api_headers: ^5.0.1
#  package_info_plus: ^4.1.0
#  web: ^1.0.0
#  geolocator: ^10.0.1



flutter:
  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - images/icons/
