name: taxi_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^2.0.0
  # BASE
  intl: ^0.18.1
  google_fonts: ^6.3.3
  html: ^0.15.4
  shared_preferences: ^2.5.4
  flutter_widget_from_html: ^0.17.1


  # TOAST
  fluttertoast: ^8.2.14

  # IMAGE
  cached_network_image: ^3.3.1

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.3.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^4.1.1
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.11
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
#  flutter_switch: ^0.3.2
#  syncfusion_flutter_charts: ^24.2.9
  syncfusion_flutter_charts: ^31.2.18

  #OTP TEXT FIELD
#  otp_text_field: ^1.1.3
  pinput: ^6.0.1
#  flutter_otp_text_field: ^1.1.3+2

  #MAP
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  location: ^8.0.1

  #IMAGES
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  date_time_picker: ^2.1.0

  #CONNECTIVITY
  package_info_plus: ^4.2.0
  http: ^0.13.6
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  map_launcher: ^4.4.2
#  lite_rolling_switch: ^1.0.1
  internet_file: ^1.3.0

  #FIREBASE
  firebase_crashlytics: ^4.3.8
  firebase_core: ^2.32.0
  firebase_auth: ^5.6.1
  firebase_storage: ^12.4.8
  firebase_database: ^11.3.8
  paginate_firestore: ^1.0.3+1
#  paginate_firestore:
#    path: ./lib/my_packages/paginate_firestore-master
  cloud_firestore: ^5.6.10

  #STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #PAYMENT GATEWAY
  razorpay_flutter: ^1.3.7
#  flutter_stripe: 11.0.0
  flutter_stripe: 10.1.1
  #  flutter_paystack: ^1.0.7
#  flutter_paystack:
#    path: ./lib/my_packages/flutter_paystack-1.0.7
#  flutter_paystack:
#    git:
#      url: https://github.com/appmeetmighty/flutter_paystack.git
#  flutter_braintree: ^4.0.0
  flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: 2.6.14
#  flutter_paytabs_bridge: ^2.6.17
  #  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  my_fatoorah: ^3.3.0
#  paytm: ^3.0.1


  rxdart: ^0.28.0


  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.4

  #SOCIAL LOGIN
  google_sign_in: ^7.2.0
  the_apple_sign_in: ^1.1.1

  #MQTT
#  mqtt_client: ^10.2.0

  #DOWNLOAD INVOICE PDF
  pdf: ^3.11.1
  pdfx: ^2.9.2
  path_provider: ^2.1.4
  open_file: ^3.5.3
#  printing: ^5.13.1
  flutter_ringtone_player: ^4.0.0+3
  permission_handler: ^12.0.1
  flutter_paypal_payment:

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.6
  cloud_firestore: ^5.6.10
  firebase_core: ^2.32.0
  google_api_headers: ^5.0.1
  package_info_plus: ^4.2.0
  # FIX Color.r / withValues issues on Flutter 3.22.3
#  stripe_platform_interface: 11.3.0
  chewie: 1.8.5
#  web: ^1.0.0



flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/flag/
    - images/ringtone.mp3


